# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      in_memory:
        memory:
          users:
            olivier:  { password: $2y$12$ZqjsZpPy8EjFL2unPVUCoOjM/VlMcrFdrUZsDm5VXLrw61RQsTeC2, roles: [ 'ROLE_USER' ] }
            jean-marc: { password: $2y$12$Mp1r7maUCK1sl3kXr4GCueduesTZbZUtasBqb3A0tYb0q89ohq7ku, roles: [ 'ROLE_ADMIN' ] }
            
    provider:     in_memory
    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
      main:
        pattern:   ^/
        anonymous: true
        form_login:
            login_path: login
            check_path: login_check
            default_target_path: /mon_espace_meditec/accueil
            always_use_default_target_path: true
        logout:
            path:       logout
            target:     login
            
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /mon_espace_meditec/.*, roles: [ROLE_ADMIN, ROLE_USER]} 
        - { path: ^/mon_espace_meditec, roles: [ROLE_ADMIN, ROLE_USER]}

