<?php

namespace MD\MeditecBundle\Repository;

/**
 * Application_ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Application_ProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
