<?php

namespace MD\MeditecBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOnlyOne(){
        $qb = $this->createQueryBuilder('a');
        $qb
            ->setMaxResults(1)
        ;
        return $qb->getQuery()->getResult();
    }
    
}
