<?php

namespace MD\MeditecBundle\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * ChiffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChiffreRepository extends EntityRepository
{
    public function findAllOrderByOrdre()
    {
        $qb = $this->createQueryBuilder('a');
        $qb
           ->orderBy('a.ordre', 'ASC')
        ;
        return $qb->getQuery()->getResult();
    }
	
}
