<?php

namespace MD\MeditecBundle\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends EntityRepository
{
	public function myFindOne($mail)
	{
            $qb = $this->createQueryBuilder('a');
            $qb
                ->where('a.mail = :mail')
                ->setParameter('mail',$mail)
            ;
            return $qb
                ->getQuery()
                ->getResult()
            ;
	}
	
}
