<?php

namespace MD\MeditecBundle\Repository;

/**
 * PartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderByOrdre()
    {
        $qb = $this->createQueryBuilder('a');
        $qb
           ->orderBy('a.ordre', 'ASC')
        ;
        return $qb->getQuery()->getResult();
    }
    public function findPublieOrderbyOdre($publier)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
           ->where('a.publier = ?1')
           ->orderBy('a.ordre', 'ASC')
           ->setParameter(1,$publier)
        ;
        return $qb->getQuery()->getResult();
    }
}
