<?php

namespace MD\MeditecBundle\Repository;

/**
 * Radiologie_ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Radiologie_ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    
}
