<?php

namespace MD\MeditecBundle\Repository;

/**
 * RadiologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadiologieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOnlyOne(){
        $qb = $this->createQueryBuilder('a');
        $qb
            ->setMaxResults(1)
        ;
        return $qb->getQuery()->getResult();
    }
}
