<?php

namespace MD\MeditecBundle\Repository;

/**
 * SauvegardeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SauvegardeRepository extends \Doctrine\ORM\EntityRepository
{
        public function findOnlyOne(){
        $qb = $this->createQueryBuilder('a');
        $qb
            ->setMaxResults(1)
        ;
        return $qb->getQuery()->getResult();
    }
    
}
